name: Build and deploy JAR app to Release

env:
  JAVA_VERSION: "17"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v2.3.1
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: "adopt"
          cache: "maven"

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: "${{ github.workspace }}/target/*.jar"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          upload_url: ${{ github.workspace }}/target/TSMP-API.jar
          tag_name: ${{ github.run_id }}
          release_name: Release ${{ github.run_id }}
          body: Release ${{ github.run_id }}, automated build by gh-actions.
          draft: false
